# Generated by Django 4.2.16 on 2024-10-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pyment_status',
            new_name='payment_status',
        ),
    ]
